eqf:
  initialGravityVariance: 1.0
  initialVelocityVariance: 1.0
  initialPointVariance: 5000.0
  biasOmegaProcessVariance: 0.0001
  biasAccelProcessVariance: 0.0001
  gravityProcessVariance: 0.01
  velocityProcessVariance: 0.1
  pointProcessVariance: 0.001
  measurementVariance: 0.003
  velOmegaVariance: 0.0001
  velAccelVariance: 0.0001
  initialBiasOmegaVariance: 1.0
  initialBiasAccelVariance: 1.0
  initialSceneDepth: 1.0
  outlierThreshold: 0.02
  fastRiccati: false
  useInnovationLift: true
  useDiscreteInnovationLift: true
  useDiscreteVelocityLift: true
  cameraOffset:
  - xw
  - -0.0216401454975
  - -0.064676986768
  - 0.00981073058949
  - 0.7123014606690344
  - -0.007707179755538301
  - 0.010499323370588468
  - 0.7017528002920512
